blank_issues_enabled: false
contact_links:
  - name: I have a question / I need help
    url: https://github.com/visgl/react-maplibre-gl/discussions
    about: Ask generic questions or request help here
